# Generated by Django 4.2.6 on 2024-03-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_resident',
            name='caretaker_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
