# Generated by Django 4.2.6 on 2024-03-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0002_flat_resident_caretaker_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_status', models.CharField(max_length=100, null=True)),
                ('book_date', models.DateField(null=True)),
                ('book_days', models.IntegerField(null=True)),
                ('book_hours', models.IntegerField(null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteusers.house_resident')),
                ('flat_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteusers.flat_resident')),
                ('paid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteusers.paid')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteusers.housemaid')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteusers.status')),
                ('work_completed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteusers.work')),
            ],
        ),
    ]
