# Generated by Django 4.2.6 on 2024-03-06 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0004_housemaid_rate_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('message', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
    ]
