# Generated by Django 4.2.7 on 2024-03-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker_approval', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='caretaker_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteusers.caretakerapproval'),
        ),
    ]
