# Generated by Django 4.2.7 on 2024-03-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0008_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteusers.status'),
        ),
    ]
